USE [AtCor]
GO

/****** Object:  StoredProcedure [dbo].[InsertCuffPWAMeasurementDetails]    Script Date: 07/13/2011 00:01:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- Batch submitted through debugger: SQLQuery2.sql|7|0|C:\Documents and Settings\smarajit.mishra\Local Settings\Temp\~vsB6.sql



CREATE PROCEDURE [dbo].[InsertCuffPWAMeasurementDetails]
(
	@systemIdentifier nvarchar(5) ,
	@groupIdentifier int ,
	@PatientNumberInternal int ,
	--@auditChange datetime ,
	@bloodPressureRange nvarchar(max) ,
	@bloodPressureEntryOption smallint ,
	@age smallint ,
	@notes nvarchar(max) ,
	@SP smallint ,
	@DP smallint ,
	@MP smallint ,
	@operator nvarchar(25),
	@weightInKilograms smallint ,
	@weightInPounds smallint ,
	@heightInCentimetres smallint ,
	@heightInInches smallint ,
	@bodyMassIndex float ,
	@memSpare1 nvarchar(50) ,
	@memSpare2 nvarchar(50) ,
	@simulation bit,
	@intSpare2 int ,
	@floatSpare1 float ,
	@datarRev int ,
	@subType nvarchar(50) ,
	@sampleRate int ,
	@signalUpSampleRate int ,
	@expPulseUpSampleRate int ,
	@flow int ,
	@medication nvarchar(max) ,
	@message nvarchar(max) ,
	@units nvarchar(max) ,
	@calSP int ,
	@calDP int ,
	@calMP int ,
	@hR int ,
	@eD int ,
	@calcED int ,
	@QualityED int ,
	@eDMin int ,
	@eDMax int ,
	@eDOther int ,
	@captureInput smallint ,
	@c_RAW_SIGNALS varbinary(max) ,
	@c_AV_PULSE varbinary(max) ,
	@c_TRIGS varbinary(50) ,
	@c_ONSETS varbinary(50) ,
	@c_Uncal_Av varbinary(50) ,
	@c_ResemblePulse varbinary(50) ,
	@c_Ole_Spare nvarchar(max),
	@c_Math_Params int ,
	@c_Sp float ,
	@c_Dp float ,
	@c_Meanp float ,
	@c_T1 float ,
	@c_T2 float ,
	@c_T1i float ,
	@c_T1r float ,
	@c_T1m float ,
	@c_T1other float ,
	@c_T2i float ,
	@c_T2R float ,
	@c_T2M float ,
	@c_T2Other float ,
	@c_Quality_T1 int ,
	@c_Quality_T2 int ,
	@c_P1 float ,
	@c_P2 float ,
	@c_T1ED float ,
	@c_T2ED float ,
	@c_Ai float ,
	@c_Esp float ,
	@c_Ap float ,
	@c_Mps float ,
	@c_Mpd float ,
	@c_Tti float ,
	@c_Dti float ,
	@c_Svi float ,
	@c_Period float ,
	@c_Dd float ,
	@c_EdPeriod float ,
	@c_DdPeriod float ,
	@c_Ph float ,
	@c_P1_Height float ,
	@c_Agph float ,
	@c_Qc_Other1 float ,
	@c_Qc_Other2 float ,
	@c_Qc_Other3 float ,
	@c_Qc_Other4 float ,
	@c_IntSpare1 int ,
	@c_IntSpare2 int ,
	@c_FloatSpare1 float ,
	@c_FloatSpare2 float ,
	@c_MemSpare1 nvarchar(max) ,
	@c_MemSpare2 nvarchar(max) ,
	@c_Al float ,
	@c_Ati float ,
	@c_Flow varbinary(50) ,
	@c_Forward varbinary(50) ,
	@c_Backward varbinary(50) ,
	@c_Avi float ,
	@c_Pptt float ,
	@c_Avd float ,
	@c_Pwv float ,
	@c_Forward_Area float ,
	@c_Backward_Area float ,
	@c_Area_Ratio float ,
	@c_Pulse_Ratio float,
	---------------------------
	@p_Raw_Signals	varbinary(MAX),
	@p_Av_Pulses	varbinary(MAX),
	@p_Trigs	varbinary(MAX),
	@p_Onsets	varbinary(MAX),
	@p_Uncal_Av	varbinary(MAX),
	@p_ResemblePulse	varbinary(MAX),
	@p_Ole_Spare	nvarchar(MAX),
	@p_Math_Params	int,
	@p_Sp	float,
	@p_Dp	float,
	@p_Meanp	float,
	@p_T1i	float,
	@p_T1r	float,
	@p_T1m	float,
	@p_T1other	float,
	@p_T2i	float,
	@p_T2r	float,
	@p_T2m	float,
	@p_T2other	float,
	@p_Max_Dpdt	float,
	@p_Memspare1	varbinary(MAX),
	@p_Memspare2	varbinary(MAX),
	@p_Intspare1	int,
	@p_Intspare2	int,
	@p_Floatspare1	float,
	@p_Floatspare2	float,
	@p_Noise_Factor	int,
	@p_Qc_Ph	float,
	@p_Qc_Phv	float,
	@p_Qc_Plv	float,
	@p_Qc_Dv	float,
	@p_Qc_Other1	float,
	@p_Qc_Other2	float,
	@p_Qc_Other3	float,
	@p_Qc_Other4	float		
)
AS
BEGIN

	DECLARE @measurementDetailsdatetime datetime2(0)
	DECLARE @auditChange datetime2(0)
	DECLARE @Pwa_id int
	BEGIN TRY
	BEGIN TRAN AddMeasurementData
	
	SET @measurementDetailsdatetime = Getdate()
	SET @auditChange = @measurementDetailsdatetime
	
		--insert into PWVMeasurement
	
		insert into  dbo.PWAMeasurement
		(
			SystemIdentifier,
			GroupIdentifier,
			PatientNumberInternal,
			StudyDateTime,
			AuditChange,
			BloodPressureRange,
			BloodPressureEntryOption,
			Age,
			Notes,
			SP,
			DP,
			MP,
			Operator,
			WeightInKilograms,
			WeightInPounds,
			HeightInCentimetres,
			HeightInInches,
			BodyMassIndex,
			MemSpare1,
			MemSpare2,
			Simulation,
			IntSpare2,
			FloatSpare1,
			DatarRev,
			SubType,
			SampleRate,
			SignalUpSampleRate,
			ExppulseUpSampleRate,
			Flow,
			Medication,
			Message,
			Units,
			CalSP,
			CalDP,
			CalMP,
			HR,
			ED,
			CalcED,
			QualityED,
			EDMin,
			EDMax,
			EDOther,
			CaptureInput,
			C_RAW_SIGNALS,
			C_AV_PULSE,
			C_TRIGS,
			C_ONSETS,
			C_Uncal_Av,
			C_ResemblePulse,
			C_Ole_Spare,
			C_Math_Params,
			C_Sp,
			C_Dp,
			C_Meanp,
			C_T1,
			C_T2,
			C_T1i,
			C_T1r,
			C_T1m,
			C_T1other,
			C_T2i,
			C_T2R,
			C_T2M,
			C_T2Other,
			C_Quality_T1,
			C_Quality_T2,
			C_P1,
			C_P2,
			C_T1ED,
			C_T2ED,
			C_Ai,
			C_Esp,
			C_Ap,
			C_Mps,
			C_Mpd,
			C_Tti,
			C_Dti,
			C_Svi,
			C_Period,
			C_Dd,
			C_EdPeriod,
			C_DdPeriod,
			C_Ph,
			C_P1_Height,
			C_Agph,
			C_Qc_Other1,
			C_Qc_Other2,
			C_Qc_Other3,
			C_Qc_Other4,
			C_IntSpare1,
			C_IntSpare2,
			C_FloatSpare1,
			C_FloatSpare2,
			C_MemSpare1,
			C_MemSpare2,
			C_Al,
			C_Ati,
			C_Flow,
			C_Forward,
			C_Backward,
			C_Avi,
			C_Pptt,
			C_Avd,
			C_Pwv,
			C_Forward_Area,
			C_Backward_Area,
			C_Area_Ratio,
			C_Pulse_Ratio
		)
		values 
		(
				@systemIdentifier,
				@groupIdentifier,
				@PatientNumberInternal,
				@measurementDetailsdatetime,
				@auditChange,
				@bloodPressureRange,
				@bloodPressureEntryOption,
				@age,
				@notes,
				@SP,
				@DP,
				@MP,
				@operator,
				@weightInKilograms,
				@weightInPounds,
				@heightInCentimetres,
				@heightInInches,
				@bodyMassIndex,
				@memSpare1 ,
				@memSpare2 ,
				@simulation ,
				@intSpare2,
				@floatSpare1,
				@datarRev,
				@subType ,
				@sampleRate,
				@signalUpSampleRate,
				@expPulseUpSampleRate,
				@flow,
				@medication,
				@message,
				@units,
				@calSP,
				@calDP,
				@calMP,
				@hR,
				@eD,
				@calcED,
				@QualityED,
				@eDMin,
				@eDMax,
				@eDOther,
				@captureInput,
				@c_RAW_SIGNALS  ,
				@c_AV_PULSE  ,
				@c_TRIGS ,
				@c_ONSETS ,
				@c_Uncal_Av ,
				@c_ResemblePulse ,
				@c_Ole_Spare ,
				@c_Math_Params,
				@c_Sp,
				@c_Dp,
				@c_Meanp,
				@c_T1,
				@c_T2,
				@c_T1i,
				@c_T1r,
				@c_T1m,
				@c_T1other,
				@c_T2i,
				@c_T2R,
				@c_T2M,
				@c_T2Other,
				@c_Quality_T1,
				@c_Quality_T2,
				@c_P1,
				@c_P2,
				@c_T1ED,
				@c_T2ED,
				@c_Ai,
				@c_Esp,
				@c_Ap,
				@c_Mps,
				@c_Mpd,
				@c_Tti,
				@c_Dti,
				@c_Svi,
				@c_Period,
				@c_Dd,
				@c_EdPeriod,
				@c_DdPeriod,
				@c_Ph,
				@c_P1_Height,
				@c_Agph,
				@c_Qc_Other1,
				@c_Qc_Other2,
				@c_Qc_Other3,
				@c_Qc_Other4,
				@c_IntSpare1,
				@c_IntSpare2,
				@c_FloatSpare1,
				@c_FloatSpare2,
				@c_MemSpare1,
				@c_MemSpare2,
				@c_Al,
				@c_Ati,
				@c_Flow ,
				@c_Forward ,
				@c_Backward ,
				@c_Avi,
				@c_Pptt,
				@c_Avd,
				@c_Pwv,
				@c_Forward_Area,
				@c_Backward_Area,
				@c_Area_Ratio,
				@c_Pulse_Ratio
		)
	
		--fetch identity value of record inserted	
		set @Pwa_id = scope_identity()
		
		--insert entry into dbo.cPWAMeasurement
		INSERT INTO dbo.cPWAMeasurement
		(
			PWA_Id,
			P_RAW_SIGNALS,
			P_AV_PULSE,
			P_TRIGS,
			P_ONSETS,
			P_UNCAL_AV,
			P_ResemblePulse,
			P_OLE_SPARE,
			P_MATH_PARAMS,
			P_SP,
			P_DP,
			P_MEANP,
			P_T1I,
			P_T1R,
			P_T1M,
			P_T1Other,
			P_T2I,
			P_T2R,
			P_T2M,
			P_T2Other,
			P_MAX_DPDT,
			P_MEMSPARE1,
			P_MEMSPARE2,
			P_INTSPARE1,
			P_INTSPARE2,
			P_FLOATSPARE1,
			P_FLOATSPARE2,
			P_NOISE_FACTOR,
			P_QC_PH,
			P_QC_PHV,
			P_QC_PLV,
			P_QC_DV,
			P_QC_OTHER1,
			P_QC_OTHER2,
			P_QC_OTHER3,
			P_QC_OTHER4
		)
		values
		(
			@Pwa_id,
			@p_Raw_Signals,
			@p_Av_Pulses,
			@p_Trigs,
			@p_Onsets,
			@p_Uncal_Av,
			@p_ResemblePulse,
			@p_Ole_Spare,
			@p_Math_Params,
			@p_Sp,
			@p_Dp,
			@p_Meanp,
			@p_T1i,
			@p_T1r,
			@p_T1m,
			@p_T1other,
			@p_T2i,
			@p_T2r,
			@p_T2m,
			@p_T2other,
			@p_Max_Dpdt,
			@p_Memspare1,
			@p_Memspare2,
			@p_Intspare1,
			@p_Intspare2,
			@p_Floatspare1,
			@p_Floatspare2,
			@p_Noise_Factor,
			@p_Qc_Ph,
			@p_Qc_Phv,
			@p_Qc_Plv,
			@p_Qc_Dv,
			@p_Qc_Other1,
			@p_Qc_Other2,
			@p_Qc_Other3,
			@p_Qc_Other4				
		)	

	COMMIT TRAN AddMeasurementData
	END TRY
	BEGIN CATCH
	 DECLARE @ErrorMessage NVARCHAR(4000);
	 --SELECT @ErrorMessage =	ERROR_MESSAGE();
		ROLLBACK TRAN AddMeasurementData
	END CATCH
	

END






GO

