/*
**
** Copyright (C) PWV MEDICAL PTY LTD, 1998
**
**
** FILE NAME     : COMMS\PUBTYPE.H
**
** PROJECT       : S32 SWCI
**
** OBJECT        : COMMS (Communications)
**
** DESCRIPTION   : Definition of objects Public types.
**
** AUTHOR        : Peter Harpas
**
** DATE CREATED  : 19/05/98
**
*/
#ifndef COMMS_PUBTYPE
#define COMMS_PUBTYPE
#include <inc/std.h>

/*
** The identifiers to use for the different databases the Database
** Manager object can manage.
** PM V9
*/
typedef enum
{
   COMMS_PORT_ONE = 1,
   COMMS_PORT_TWO,
   COMMS_PORT_THREE,
   COMMS_PORT_FOUR,
   COMMS_PORT_FIVE,
   COMMS_PORT_SIX,
   COMMS_PORT_SEVEN,
   COMMS_PORT_EIGHT,
   COMMS_PORT_NINE,
   COMMS_PORT_TEN,
   COMMS_PORT_ELEVEN,
   COMMS_PORT_TWELVE,
   COMMS_PORT_THIRTEEN,
   COMMS_PORT_FOURTEEN,
   COMMS_PORT_FIFTEEN,
   COMMS_PORT_SIXTEEN,
   COMMS_PORT_SEVENTEEN,
   COMMS_PORT_EIGHTEEN,
   COMMS_PORT_NINETEEN,
   COMMS_PORT_TWENTY,
   COMMS_PORT_TWENTYONE,
   COMMS_PORT_TWENTYTWO,
   COMMS_PORT_TWENTYTHREE,
   COMMS_PORT_TWENTYFOUR,
   COMMS_PORT_TWENTYFIVE,
   COMMS_PORT_TWENTYSIX,
   COMMS_PORT_TWENTYSEVEN,
   COMMS_PORT_TWENTYEIGHT,
   COMMS_PORT_TWENTYNINE,
   COMMS_PORT_USB,
   COMMS_PORT_SIMULATE
} COMMS_ID_TYPE;

typedef enum
{
   COMMS_FOOTSWITCH_NONE,
   COMMS_FOOTSWITCH_ONE,
   COMMS_FOOTSWITCH_TWO
} COMMS_FOOTSWITCH_STATUS_TYPE;

const String COMMS_OLD_MODULE_STRING = "EM2/MM2";
const String COMMS_MM3_MODULE_STRING = "MM3";
const String COMMS_USB_MODULE_STRING = "USB";
const String COMMS_EM3_MODULE_STRING = "EM3";
const String COMMS_MM4_MODULE_STRING = "MM4";
const String COMMS_UNKNOWN_MODULE_STRING = "";


#endif
